
services:
  globant-database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: globant
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  globant-app:
    image: globant_app #globant_app
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - globant-database
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:admin@globant-database:5432/globant


volumes:
  pgdata: