services:
  globant_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: globant
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  globant_app:
    image: globant_app
    # entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - globant_database
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:admin@globant_database:5432/globant

volumes:
  pgdata: